---
abstract: ~
author:
  - 'Ryuzo Yamamoto <ryuzo.yamamoto@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-GitSmartHttp
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cwd: 0
  File::Spec: 0
  File::Which: 0
  File::chdir: 0
  HTTP::Date: 0
  IPC::Open3: 0
  Plack: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dragon3/Plack-App-GitSmartHttp.git
version: 0.02
